/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer para añadir un paso a una rama.
 */
export interface AddStep { 
    /**
     * Contenido del paso
     */
    content: any | null;
}

