/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer para crear una nueva rama.
 */
export interface CreateBranch { 
    /**
     * Nombre de la nueva rama
     */
    name: string;
    /**
     * Rama padre desde la cual ramificar
     */
    from_branch: string;
    /**
     * Número de paso (1-indexed) donde iniciar la nueva rama
     */
    at_step: number;
}

