/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `running` - Running * `completed` - Completed * `failed` - Failed * `partial` - Partial
 */
export enum ExecutionSnapshotStatusEnum {

    Running = 'running',

    Completed = 'completed',

    Failed = 'failed',

    Partial = 'partial'
}

