/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutionSnapshotStatusEnum } from './executionSnapshotStatusEnum';
import { StepExecution } from './stepExecution';


export interface ExecutionSnapshot { 
    readonly id: number;
    flow_version: number;
    readonly created_at: string;
    readonly triggered_by: number;
    metadata?: any | null;
    status?: ExecutionSnapshotStatusEnum;
    readonly step_executions: Array<StepExecution>;
}



