/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FamilyProperty } from './familyProperty';


/**
 * Serializador para familias con propiedades anidadas y tipado fuerte.
 */
export interface Family { 
    readonly id: number;
    name?: string;
    description?: string;
    family_hash: string;
    provenance: string;
    frozen?: boolean;
    metadata?: any | null;
    readonly created_at: string;
    readonly updated_at: string;
    readonly created_by: number | null;
    readonly updated_by: number | null;
    readonly properties: Array<FamilyProperty>;
    /**
     * Get family aggregated properties using type-safe interface.
     */
    readonly aggregated_properties: { [key: string]: any; };
    /**
     * Get member property statistics using type-safe interface.
     */
    readonly member_statistics: { [key: string]: any; };
}

