/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FamilyProperty } from './familyProperty';


/**
 * Serializador para familias con propiedades anidadas.
 */
export interface Family { 
    readonly id: number;
    name?: string;
    description?: string;
    family_hash: string;
    provenance: string;
    frozen?: boolean;
    metadata?: any | null;
    readonly created_at: string;
    readonly properties: Array<FamilyProperty>;
}

