/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializador para membresía molécula-familia.
 */
export interface FamilyMember { 
    readonly id: number;
    family: number;
    molecule: number;
}

