/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer para nodos del árbol de flujo.
 */
export interface FlowNode { 
    readonly id: number;
    flow: number;
    parent?: number | null;
    content: any | null;
    readonly content_hash: string;
    readonly created_at: string;
    readonly created_by: number;
}

