/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer para ramas del flujo.
 */
export interface FlowBranch { 
    readonly id: number;
    flow: number;
    name: string;
    readonly head: number;
    readonly start_node: number;
    parent_branch?: number | null;
    readonly created_at: string;
    readonly created_by: number;
    readonly path_length: string;
}

