/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Step } from './step';


export interface FlowVersion { 
    readonly id: number;
    flow: number;
    version_number: number;
    parent_version?: number | null;
    readonly created_at: string;
    readonly created_by: number;
    metadata?: any | null;
    is_frozen?: boolean;
    readonly steps: Array<Step>;
}

