/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MolecularProperty } from './molecularProperty';


/**
 * Serializador para moléculas con propiedades anidadas.
 */
export interface Molecule { 
    readonly id: number;
    name?: string;
    inchikey?: string | null;
    smiles?: string;
    inchi?: string;
    canonical_smiles?: string;
    molecular_formula?: string;
    metadata?: any | null;
    readonly frozen: boolean;
    readonly created_at: string;
    readonly created_by: number;
    readonly properties: Array<MolecularProperty>;
}

