/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedArtifact { 
    readonly id?: number;
    sha256?: string;
    filename?: string;
    content_type?: string;
    size?: number;
    storage_path?: string;
    metadata?: any | null;
    readonly created_at?: string;
    readonly created_by?: number;
}

