/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface PatchedUser { 
    readonly id?: number;
    /**
     * Obligatorio. Longitud máxima 150 caracteres alfanuméricos. Letras, dígitos y @/./+/-/_ únicamente.
     */
    username?: string;
    email?: string;
    first_name?: string;
    last_name?: string;
    university?: string;
    /**
     * Indica si el usuario debe ser tratado como un usuario activo. Desactive este campo en lugar de eliminar usuarios.
     */
    is_active?: boolean;
    readonly roles?: Array<Role>;
    role_ids?: Array<number>;
    readonly created_at?: string;
    readonly updated_at?: string;
}

