/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializador para propiedades moleculares EAV.
 */
export interface PatchedMolecularProperty { 
    readonly id?: number;
    molecule?: number;
    property_type?: string;
    value?: string;
    is_invariant?: boolean;
    method?: string;
    units?: string;
    relation?: string;
    source_id?: string;
    metadata?: any | null;
    readonly created_at?: string;
}

