/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowVersion } from './flowVersion';


export interface PatchedFlow { 
    readonly id?: number;
    name?: string;
    description?: string;
    readonly owner?: number;
    readonly created_at?: string;
    readonly updated_at?: string;
    readonly current_version?: FlowVersion;
    readonly versions?: Array<FlowVersion>;
}

