/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriorityEnum } from './priorityEnum';
import { TypeEnum } from './typeEnum';


/**
 * Serializer para notificaciones de usuario.
 */
export interface PatchedUserNotification { 
    readonly id?: number;
    type?: TypeEnum;
    title?: string;
    message?: string;
    priority?: PriorityEnum;
    read?: boolean;
    readonly created_at?: string;
    readonly read_at?: string | null;
    metadata?: any | null;
}



