/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `low` - Baja * `normal` - Normal * `high` - Alta * `urgent` - Urgente
 */
export enum PriorityEnum {

    Low = 'low',

    Normal = 'normal',

    High = 'high',

    Urgent = 'urgent'
}

