/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';


export interface Role { 
    readonly id: number;
    name: string;
    description?: string;
    readonly permissions: Array<Permission>;
    permission_ids?: Array<number>;
    readonly created_at: string;
    readonly updated_at: string;
}

