/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StepExecutionStatusEnum } from './stepExecutionStatusEnum';
import { StepExecutionArtifact } from './stepExecutionArtifact';


export interface StepExecution { 
    readonly id: number;
    step: number;
    execution_snapshot: number;
    readonly started_at: string;
    completed_at?: string | null;
    status?: StepExecutionStatusEnum;
    inputs?: any | null;
    outputs?: any | null;
    error_message?: string;
    readonly execution_artifacts: Array<StepExecutionArtifact>;
}



