/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - Pending * `running` - Running * `completed` - Completed * `failed` - Failed * `cancelled` - Cancelled
 */
export enum StepExecutionStatusEnum {

    Pending = 'pending',

    Running = 'running',

    Completed = 'completed',

    Failed = 'failed',

    Cancelled = 'cancelled'
}

