/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Step { 
    readonly id: number;
    flow_version: number;
    name: string;
    description?: string;
    step_type: string;
    order: number;
    config?: any | null;
    dependencies?: Array<number>;
    readonly created_at: string;
    readonly updated_at: string;
}

