/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Artifact } from './artifact';


export interface StepExecutionArtifact { 
    readonly id: number;
    step_execution: number;
    readonly artifact: Artifact;
    artifact_type: string;
}

