/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `info` - Información * `success` - Éxito * `warning` - Advertencia * `error` - Error * `flow_update` - Actualización de Flujo * `system` - Sistema
 */
export enum TypeEnum {

    Info = 'info',

    Success = 'success',

    Warning = 'warning',

    Error = 'error',

    FlowUpdate = 'flow_update',

    System = 'system'
}

