/**
 * ChemFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreate { 
    /**
     * Obligatorio. Longitud máxima 150 caracteres alfanuméricos. Letras, dígitos y @/./+/-/_ únicamente.
     */
    username: string;
    email?: string;
    first_name?: string;
    last_name?: string;
    university?: string;
    password: string;
    password2: string;
    role_ids?: Array<number>;
}

