"""Type stubs for rest_framework.status."""

HTTP_200_OK: int
HTTP_201_CREATED: int
HTTP_204_NO_CONTENT: int
HTTP_400_BAD_REQUEST: int
HTTP_401_UNAUTHORIZED: int
HTTP_403_FORBIDDEN: int
HTTP_404_NOT_FOUND: int
HTTP_405_METHOD_NOT_ALLOWED: int
HTTP_409_CONFLICT: int
HTTP_500_INTERNAL_SERVER_ERROR: int
