"""Type stubs for rest_framework.viewsets."""

from typing import Any, List, Optional, TypeVar

from django.db.models import Model, QuerySet
from django.http import HttpRequest

from .response import Response
from .serializers import Serializer

_MT = TypeVar("_MT", bound=Model)


class ViewSetMixin:
    """Mixin for ViewSet support."""

    action: Optional[str]
    request: HttpRequest
    format_kwarg: Optional[str]

    def get_serializer_class(self) -> type[Serializer]: ...
    def get_serializer(self, *args: Any, **kwargs: Any) -> Serializer: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_object(self) -> Model: ...
    def get_permissions(self) -> List[Any]: ...
    def perform_create(self, serializer: Serializer) -> None: ...
    def perform_update(self, serializer: Serializer) -> None: ...
    def perform_destroy(self, instance: Model) -> None: ...
    def paginate_queryset(self, queryset: QuerySet[Any]) -> Optional[List[Any]]: ...
    def get_paginated_response(self, data: Any) -> Response: ...
    def get_success_headers(self, data: Any) -> dict[str, str]: ...

class ViewSet(ViewSetMixin):
    """Base ViewSet class."""

    pass

class GenericViewSet(ViewSetMixin):
    """Generic ViewSet with queryset support."""

    queryset: Optional[QuerySet[Any]]

class ModelViewSet(GenericViewSet):
    """Full CRUD operations viewset."""

    def create(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...
    def retrieve(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...
    def update(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...
    def partial_update(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> Response: ...
    def destroy(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...
    def list(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...

class ReadOnlyModelViewSet(GenericViewSet):
    """Read-only operations viewset."""

    def retrieve(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...
    def list(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Response: ...
