# Generated by Django 5.2.7 on 2025-10-20 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Molecule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("formula", models.CharField(blank=True, max_length=200)),
                ("smiles", models.CharField(blank=True, max_length=500)),
                ("inchi", models.TextField(blank=True)),
                ("molecular_weight", models.FloatField(blank=True, null=True)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molecules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("protocol_type", models.CharField(max_length=100)),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("safety_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("reaction_type", models.CharField(max_length=100)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("yield_percentage", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("instruction", models.TextField()),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Temperature in Celsius", null=True
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_steps",
                        to="chemistry.protocol",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("protocol", "order")},
            },
        ),
        migrations.CreateModel(
            name="MoleculeRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stoichiometry", models.FloatField(default=1.0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reactant", "Reactant"),
                            ("product", "Product"),
                            ("catalyst", "Catalyst"),
                            ("solvent", "Solvent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reaction_refs",
                        to="chemistry.molecule",
                    ),
                ),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molecule_refs",
                        to="chemistry.reaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("reaction", "molecule", "role")},
            },
        ),
    ]
