# Generated by assistant to add MoleculeFlow.role and step_number
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemistry", "0002_seed_chon_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="moleculeflow",
            name="role",
            field=models.CharField(blank=True, max_length=50, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moleculeflow",
            name="step_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
