# Generated by Django 5.2.7 on 2025-10-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemistry", "0001_initial"),
        ("flows", "0002_flownode_flowbranch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("family_hash", models.CharField(max_length=128)),
                ("provenance", models.CharField(max_length=200)),
                ("frozen", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="molecule",
            options={"ordering": ["name", "inchikey"]},
        ),
        migrations.RemoveField(
            model_name="molecule",
            name="formula",
        ),
        migrations.RemoveField(
            model_name="molecule",
            name="molecular_weight",
        ),
        migrations.RemoveField(
            model_name="molecule",
            name="properties",
        ),
        migrations.AddField(
            model_name="molecule",
            name="canonical_smiles",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="molecule",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="molecule",
            name="inchikey",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=27,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="molecule",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="molecule",
            name="molecular_formula",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="smiles",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chemistry.family",
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to="chemistry.molecule",
                    ),
                ),
            ],
            options={
                "unique_together": {("family", "molecule")},
            },
        ),
        migrations.CreateModel(
            name="FamilyProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_type", models.CharField(max_length=200)),
                ("value", models.TextField()),
                ("is_invariant", models.BooleanField(default=False)),
                ("method", models.CharField(blank=True, max_length=100)),
                ("units", models.CharField(blank=True, max_length=50)),
                ("relation", models.CharField(blank=True, max_length=10)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="chemistry.family",
                    ),
                ),
            ],
            options={
                "ordering": ["property_type", "created_at"],
                "unique_together": {("family", "property_type", "method")},
            },
        ),
        migrations.CreateModel(
            name="MolecularProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_type", models.CharField(max_length=200)),
                ("value", models.TextField()),
                ("is_invariant", models.BooleanField(default=False)),
                ("method", models.CharField(blank=True, max_length=100)),
                ("units", models.CharField(blank=True, max_length=50)),
                ("relation", models.CharField(blank=True, max_length=10)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="chemistry.molecule",
                    ),
                ),
            ],
            options={
                "ordering": ["property_type", "created_at"],
                "unique_together": {("molecule", "property_type", "method")},
            },
        ),
        migrations.CreateModel(
            name="MoleculeFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_molecules",
                        to="flows.flow",
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_links",
                        to="chemistry.molecule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("flow", "molecule")},
            },
        ),
        migrations.DeleteModel(
            name="MoleculeRef",
        ),
        migrations.DeleteModel(
            name="ProtocolStep",
        ),
        migrations.DeleteModel(
            name="Protocol",
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
    ]
