# Generated by Django 5.2 on 2025-11-02
import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemistry", "0002_seed_chon_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "execution_id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, db_index=True)),
                ("provider_name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        max_length=32,
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                            ("waiting_retry", "waiting_retry"),
                            ("waiting_resume", "waiting_resume"),
                            ("broken", "broken"),
                        ],
                        default="pending",
                    ),
                ),
                ("payload", models.JSONField()),
                ("error", models.TextField(null=True, blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["idempotency_key"], name="chemistry_exe_idempt_idx"
                    ),
                    models.Index(
                        fields=["provider_name", "status"],
                        name="chemistry_exe_provstat_idx",
                    ),
                ],
                "app_label": "chemistry",
            },
        ),
        migrations.AddConstraint(
            model_name="execution",
            constraint=models.UniqueConstraint(
                fields=["provider_name", "idempotency_key"],
                name="uq_provider_idempotency",
            ),
        ),
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        auto_created=True,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=128)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="chemistry.execution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "app_label": "chemistry",
                "unique_together": {("execution", "step", "version")},
            },
        ),
        migrations.CreateModel(
            name="OutboxEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        auto_created=True,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed", models.BooleanField(default=False)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="outbox_entries",
                        to="chemistry.execution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["processed"], name="chemistry_outbox_processed_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="chemistry_outbox_event_idx"
                    ),
                ],
                "app_label": "chemistry",
            },
        ),
    ]
