# Generated by Django 5.2 on 2025-11-02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemistry", "0002_moleculeflow_add_role_step_number"),
        ("chemistry", "0003_external_jobs"),
    ]

    operations = []
