# Generated by Django 5.2.7 on 2025-11-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemistry", "0004_merge_0002_moleculeflow_and_0003_external_jobs"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="execution",
            new_name="chemistry_e_idempot_1034b2_idx",
            old_name="chemistry_exe_idempt_idx",
        ),
        migrations.RenameIndex(
            model_name="execution",
            new_name="chemistry_e_provide_4b555a_idx",
            old_name="chemistry_exe_provstat_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxentry",
            new_name="chemistry_o_process_40b749_idx",
            old_name="chemistry_outbox_processed_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxentry",
            new_name="chemistry_o_event_t_5d7059_idx",
            old_name="chemistry_outbox_event_idx",
        ),
        migrations.AlterField(
            model_name="checkpoint",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("waiting_retry", "Waiting Retry"),
                    ("waiting_resume", "Waiting Resume"),
                    ("broken", "Broken"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="outboxentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
